#!/usr/bin/env bash
# ^ Tells the OS to run this file with bash (adjust if you prefer zsh).

# Automates repeated commands for your dev environment.

# Example command usage:
#   dev init 
#
# Options:
#   init   : Initialize development environment (like environment variables, etc.)
#   clean  : Clean back test files

# Turn on exit-on-error
set -e

# Turn on command tracing
# set -x

# Define color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color / Reset

# Helper function to show usage
usage() {
  echo -e "${GREEN}Usage: $0 {init|backtest|debug|clean}${NC}"
  exit 1
}

write_env_file_if_not_exists() {
  local env_file="$1"
  if [ ! -f "$env_file" ]; then
    echo -e "${GREEN}Creating $env_file ...${NC}"
    touch "$env_file"
    echo 'export PATH="$PATH:$(pwd)"' >> "$env_file"
    echo "export QUANT_CONNECT_USER_ID=?" >> "$env_file"
    echo "export QUANT_CONNECT_API_TOKEN=?" >> "$env_file"
    echo -e "${GREEN}$env_file created successfully.${NC}" 
  else
    echo -e "${GREEN}$env_file already exists. Skipping creation.${NC}"
  fi
}

# Function to initialize the environment
init_environment() {
  echo -e "${GREEN}Initializing environment ...${NC}"
  eval "$(conda shell.bash hook)"

  if [ -d ".dgquant-venv" ]; then
    read -p ".dgquant-venv virtual env already exists and will be deleted and re-created. Do you want to proceed? (y/n): " choice
    case "$choice" in
      y|Y) 
        echo -e "${GREEN}Proceeding with initialization ...${NC}"
        echo -e "${GREEN}Deleting existing virtual environment ...${NC}"
        conda remove -p ./.dgquant-venv --all -y
        ;;
      n|N) 
        echo -e "${GREEN}Initialization aborted.${NC}"; 
        exit 0
        ;;
      *) 
        echo -e "${GREEN}Invalid choice. Initialization aborted.${NC}"; 
        exit 1
        ;;
    esac
  fi

  write_env_file_if_not_exists ".env"

  echo -e "${GREEN}Creating virtual Python environment ./.dgquant-venv ...${NC}"
  conda env create -f environment.yml -p ./.dgquant-venv
  
  echo -e "${GREEN}Initializing Conda ...${NC}"
  conda init
  
  echo -e "${GREEN}Activating virtual environment to install packages from ./environment.yml ...${NC}"
  conda activate ./.dgquant-venv
  
  echo -e "${GREEN}Installing Lean CLI ...${NC}"
  pip install lean

  echo -e "${GREEN}Setting Lean Engine configuration file to ensure consistent version of Lean engine and project type definition package see ~/.lean/config${NC}"
  lean config set engine-image quantconnect/lean:17371
  lean config set research-image quantconnect/research:17371
  
  echo ""
  echo -e "${BLUE}Run 'conda activate ./.dgquant-venv' to activate the virtual environment${NC}"; 
  echo -e "${BLUE}If new .env file was created make sure to set environmental variables for Quant Connect auth${NC}"
   
}

# Function to clean up generated files
clean_backtest_files() {
  echo -e "${GREEN}Cleaning up backtest folder ...${NC}"
  rm -rf alg/backtests/*
}

backtest() {
  lean backtest alg
}

debug() {
  echo -e "${GREEN}Go to debug tab in VSCode, select Debug with Lean CLI profile, and press on green arrow button to run debugger${NC}" 
  lean backtest alg  --debug debugpy
}

# If no arguments provided, show usage
[[ $# -eq 0 ]] && usage

# The first argument is the command
COMMAND=$1
shift  # Shifts positional parameters to the left so $2 becomes $1, etc.

case $COMMAND in
  init)
    init_environment
    ;;
  clean)
    clean_backtest_files
    ;;
  backtest)
    backtest
    ;;
  debug)
    debug
    ;;
  *)
    usage
    ;;
esac